@startuml
  !include packages/entities/authentication.puml
  !include packages/entities/authorization.puml
  !include packages/entities/mercatus.puml
  !include packages/entities/catalog.puml
  !include packages/entities/network-catalog.puml
  !include packages/entities/library-catalog.puml
  !include packages/entities/tenda.puml
  !include packages/entities/scanner.puml

  access --|> user : <<uses>>
  itemEntity --|> product : <<extends>>
  itemEntity --|> barcode : <<uses>>
  product --|> barcode : <<uses>>
  basket --|> itemEntity : <<uses>>
  position --|> itemEntity : <<uses>>

@enduml
