@startuml
' User interfaces'
!include packages/gui/inventarium-gui.puml
!include packages/gui/inventarium-gui-sequitur.puml
!include packages/gui/inventarium-gui-mercator.puml
!include packages/gui/inventarium-gui-admob.puml

'Bussines logic'
!include packages/core/inventarium-core.puml
!include packages/core/inventarium-sequitur.puml
!include packages/core/inventarium-mercator.puml
!include packages/core/inventarium-admob.puml

'Implementation'
inventariumServiceInterface <|-- inventariumMercatorServiceClass
inventariumServiceInterface <|-- inventariumSequiturServiceClass
inventariumServiceInterface <|-- inventariumAdmobServiceClass

' Distribution'


'External dependencies'
inventariumAdmobServiceClass --|> ionicNativeAdmob

inventariumGuiClass <|-- inventariumGuiMercatorClass
inventariumGuiClass <|-- inventariumGuiSequiturClass
inventariumGuiClass <|-- inventariumGuiAdmobClass

@enduml
